# fullsend per-repo configuration
# https://github.com/fullsend-ai/fullsend
#
# This file configures fullsend for per-repo installation mode.
# See https://fullsend.sh/docs/guides/infrastructure/layered-config-reference
version: "1"
runtime: dummy
roles:
    - triage
    - coder
    - review
    - fix
    - retro
    - prioritize
agents:
    - name: local-base
      source: harness/local-base.yaml
    - name: local-child
      source: harness/local-child.yaml
    - name: remote-base-child
      source: harness/remote-base-child.yaml
    - name: remote-child
      source: https://raw.githubusercontent.com/halfsend-08/test-repo-07-base-harness-host/main/harness/remote-child.yaml#sha256=6b334e04393620575e02dec010d26348042539013ba4a55f1161a1d484ed1c75
allowed_remote_resources:
    - https://raw.githubusercontent.com/fullsend-ai/fullsend/
    - https://raw.githubusercontent.com/fullsend-ai/agents/
    - https://raw.githubusercontent.com/halfsend-08/test-repo-07-base-harness-host/
create_issues:
    allow_targets:
        repos:
            - halfsend-08/test-repo-07
            - fullsend-ai/fullsend
mint_url: https://bt-3e3a58a3-bt-mint.fullsend-ai.workers.dev
inference:
    project: it-gcp-konflux-e2e-fullsend
    wif_provider: projects/208332380190/locations/global/workloadIdentityPools/fullsend-inference/providers/gh-halfsend-08-test-repo-07
